version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: anshul
      POSTGRES_DB: cr45_reduced
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://postgres:anshul@db:5432/cr45_reduced?sslmode=disable
      HTTP_ADDR: :8080
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: on-failure

volumes:
  db_data:
